# Generated by Django 4.0.1 on 2022-05-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assignment_result_delete_book_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_register',
            old_name='password_r',
            new_name='name',
        ),
    ]
